version: '3'

services:
    webapp:
        container_name: ilmalammitys.net
        image: yedor/ilmalammitys.net:1.0
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5123:80"
