/*
 * Copyright (c) 2020.  Olli-Pekka Wallin All rights reserved
 */

export const UPDATE_GADGET_DROPDOWN_CHOICE = "UPDATE_GADGET_DROPDOWN_CHOICE";
export const ADD_GADGET_DROPDOWN_DEVICE = "ADD_GADGET_DROPDOWN_DEVICE";
export const SET_GADGET_DROPDOWN_DEVICE = "SET_GADGET_DROPDOWN_DEVICE";